### ISSUE TITLE
Consolidate regular opening hours in listing when they are the same consecutively

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-quando#10]
When we have, say, regular hour schedules in consecutive days that are the same, e.g.

```YAML
regular:
  tuesday:
    - opens: "10:00"
      shuts: "13:00"
  wednesday:
    - opens: "10:00"
      shuts: "13:00"
  thursday:
    - opens: "10:00"
      shuts: "13:00"
```
Rather than outputting:

**Tuesdays:** 10am-1pm
**Wednesdays:** 10am-1pm
**Thursdays:** 10am-1pm

.. (somehow) be smart and output:
**Tuesdays-Thursdays:** 10am-1pm

Although in terms of inline machine readability and microdata, this may be a fail.
