### ISSUE TITLE
Exceptions within periods aren't listed in exceptions template

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-quando#16]
This has just come up. Reasonably obscure and there is a workaround. Business has limited operation hours for a period because of Covid-19 lockdown, and I need to include Good Friday and Easter Monday as exceptions within the period because they are non-operational days. The problem is that the [exceptions display template](https://github.com/hughbris/grav-plugin-quando/blob/develop/templates/partials/hours_exceptions.html.twig) does not recurse into the periods for exceptions.

Easily worked around by duplicating the period exceptions at the outer level, but not ideal.

Ideal:
```yaml
    periods:
      - begin: "2020-03-26"
        end: "2020-04-23"
        description: Emergency operation hours
        name: "COVID-19 lockdown"
        regular:
          monday:
            - opens: "09:00"
              shuts: "16:00"

          # YADA YADA …

          friday:
            - opens: "09:00"
              shuts: "16:00"
        exceptions:
          '2020-04-10':
            hours: []
            comment: 'Good Friday'
          '2020-04-13':
            hours: []
            comment: 'Easter Monday'
```

Workaround:
```yaml
    regular:
      # YADA YADA …
    exceptions:
      '2020-04-10': # has to be added redundantly
        hours: []
        comment: 'Good Friday'
      '2020-04-13': # has to be added redundantly
        hours: []
        comment: 'Easter Monday'
    periods:
      - begin: "2020-03-26"
        end: "2020-04-23"
        description: Emergency operation hours
        name: "COVID-19 lockdown"
        regular:
          # YADA YADA as above with duplication …
